//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudConcerts3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.ArtistConcerts = new HashSet<ArtistConcert>();
            this.ArtistGigs = new HashSet<ArtistGig>();
            this.ListenerArtists = new HashSet<ListenerArtist>();
            this.Members = new HashSet<Member>();
        }
    
        public string Id { get; set; }
        public string StageName { get; set; }
        public string Description { get; set; }
        public Nullable<int> GenreID { get; set; }
        public string ImageURL { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual ICollection<ArtistConcert> ArtistConcerts { get; set; }
        public virtual ICollection<ArtistGig> ArtistGigs { get; set; }
        public virtual ICollection<ListenerArtist> ListenerArtists { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}
