//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudConcerts3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CloudConcertsDataEntities : DbContext
    {
        public CloudConcertsDataEntities()
            : base("name=CloudConcertsDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<ArtistConcert> ArtistConcerts { get; set; }
        public virtual DbSet<ArtistGig> ArtistGigs { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Concert> Concerts { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Gig> Gigs { get; set; }
        public virtual DbSet<GigGenre> GigGenres { get; set; }
        public virtual DbSet<Host> Hosts { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<Listener> Listeners { get; set; }
        public virtual DbSet<ListenerArtist> ListenerArtists { get; set; }
        public virtual DbSet<ListenerGenre> ListenerGenres { get; set; }
        public virtual DbSet<Member> Members { get; set; }
    }
}
