//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudConcerts3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concert
    {
        public Concert()
        {
            this.ArtistConcerts = new HashSet<ArtistConcert>();
        }
    
        public int ConcertID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string HostID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal TicketPrice { get; set; }
        public bool isPublic { get; set; }
    
        public virtual ICollection<ArtistConcert> ArtistConcerts { get; set; }
        public virtual Host Host { get; set; }
    }
}
