//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudConcerts3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Artists = new HashSet<Artist>();
            this.GigGenres = new HashSet<GigGenre>();
            this.ListenerGenres = new HashSet<ListenerGenre>();
        }
    
        public int GenreID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Artist> Artists { get; set; }
        public virtual ICollection<GigGenre> GigGenres { get; set; }
        public virtual ICollection<ListenerGenre> ListenerGenres { get; set; }
    }
}
