//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudConcerts3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gig
    {
        public Gig()
        {
            this.ArtistGigs = new HashSet<ArtistGig>();
            this.GigGenres = new HashSet<GigGenre>();
        }
    
        public int GigID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string HostID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal Compensation { get; set; }
        public bool isPublic { get; set; }
    
        public virtual ICollection<ArtistGig> ArtistGigs { get; set; }
        public virtual Host Host { get; set; }
        public virtual ICollection<GigGenre> GigGenres { get; set; }
    }
}
